-- BharatANPR prototype database
-- Source of truth: append-only detections. "Today" and historical days are views.
-- Apply through a Supabase migration after selecting a development project/branch.

create schema if not exists extensions;
create schema if not exists gis;
create extension if not exists postgis with schema gis;
create extension if not exists pgcrypto with schema extensions;
create extension if not exists pg_trgm with schema extensions;

do $$ begin
  create type public.operator_role as enum (
    'viewer', 'operator', 'investigator', 'supervisor', 'administrator'
  );
exception when duplicate_object then null;
end $$;

do $$ begin
  create type public.camera_status as enum ('online', 'degraded', 'offline', 'maintenance');
exception when duplicate_object then null;
end $$;

do $$ begin
  create type public.alert_status as enum ('new', 'in_review', 'pending', 'resolved', 'dismissed');
exception when duplicate_object then null;
end $$;

do $$ begin
  create type public.case_status as enum ('live', 'pending', 'resolved', 'closed');
exception when duplicate_object then null;
end $$;

create table if not exists public.jurisdictions (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  state_code text not null,
  timezone text not null default 'Asia/Kolkata',
  boundary gis.geometry(MultiPolygon, 4326),
  created_at timestamptz not null default now(),
  unique (state_code, name)
);

create table if not exists public.operator_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  jurisdiction_id uuid not null references public.jurisdictions(id),
  display_name text not null,
  role public.operator_role not null default 'viewer',
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.cameras (
  id uuid primary key default gen_random_uuid(),
  jurisdiction_id uuid not null references public.jurisdictions(id),
  external_ref text not null,
  name text not null,
  location gis.geography(Point, 4326) not null,
  bearing_degrees numeric(6, 2),
  lane_labels text[] not null default '{}',
  status public.camera_status not null default 'offline',
  clock_offset_ms integer not null default 0,
  last_heartbeat_at timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (jurisdiction_id, external_ref),
  check (bearing_degrees is null or (bearing_degrees >= 0 and bearing_degrees < 360))
);

-- Prototype/mock registry adapter cache. Never expose this table directly to clients.
create table if not exists public.registry_vehicle_snapshots (
  id uuid primary key default gen_random_uuid(),
  jurisdiction_id uuid not null references public.jurisdictions(id),
  plate_token text not null,
  registry_source text not null,
  registration_status text,
  vehicle_class text,
  make text,
  model text,
  registered_colour text,
  response_payload jsonb not null default '{}'::jsonb,
  retrieved_at timestamptz not null,
  expires_at timestamptz,
  is_synthetic boolean not null default true,
  created_at timestamptz not null default now(),
  unique (jurisdiction_id, plate_token, registry_source, retrieved_at)
);

-- plate_token is an HMAC-SHA-256 generated by the Python/Java backend, not a plain hash.
-- Raw plate text and owner identity are intentionally absent.
create table if not exists public.detections (
  id uuid primary key default gen_random_uuid(),
  jurisdiction_id uuid not null references public.jurisdictions(id),
  camera_id uuid not null references public.cameras(id),
  source_event_id text not null,
  captured_at timestamptz not null,
  observed_on date not null,
  ingested_at timestamptz not null default now(),
  plate_token text,
  plate_masked text,
  ocr_text_synthetic text,
  ocr_confidence numeric(5, 4),
  vehicle_track_ref text,
  lane_label text,
  direction text,
  speed_kph numeric(7, 2),
  location gis.geography(Point, 4326) not null,
  observed_vehicle_class text,
  observed_make_family text,
  observed_model_family text,
  observed_colour text,
  attribute_confidence numeric(5, 4),
  registry_snapshot_id uuid references public.registry_vehicle_snapshots(id),
  identity_consistency_score numeric(5, 4),
  is_watchlist_candidate boolean not null default false,
  is_simulated boolean not null default true,
  model_versions jsonb not null default '{}'::jsonb,
  quality jsonb not null default '{}'::jsonb,
  evidence_object_path text,
  evidence_sha256 text,
  created_at timestamptz not null default now(),
  unique (camera_id, source_event_id),
  check (ocr_confidence is null or (ocr_confidence >= 0 and ocr_confidence <= 1)),
  check (attribute_confidence is null or (attribute_confidence >= 0 and attribute_confidence <= 1)),
  check (identity_consistency_score is null or (identity_consistency_score >= 0 and identity_consistency_score <= 1)),
  check (speed_kph is null or speed_kph >= 0),
  check (ocr_text_synthetic is null or is_simulated)
);

create table if not exists public.detection_ocr_candidates (
  detection_id uuid not null references public.detections(id) on delete cascade,
  rank smallint not null,
  candidate_text_synthetic text,
  candidate_token text,
  confidence numeric(5, 4) not null,
  character_confidences jsonb not null default '[]'::jsonb,
  primary key (detection_id, rank),
  check (rank > 0),
  check (confidence >= 0 and confidence <= 1)
);

create table if not exists public.alerts (
  id uuid primary key default gen_random_uuid(),
  jurisdiction_id uuid not null references public.jurisdictions(id),
  plate_token text,
  plate_masked text,
  alert_type text not null,
  severity smallint not null,
  status public.alert_status not null default 'new',
  confidence numeric(5, 4) not null,
  title text not null,
  explanation jsonb not null,
  contrary_evidence jsonb not null default '[]'::jsonb,
  rule_version text not null,
  first_seen_at timestamptz not null,
  last_seen_at timestamptz not null,
  assigned_to uuid references auth.users(id),
  resolved_by uuid references auth.users(id),
  resolution_code text,
  resolution_note text,
  resolved_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (severity between 1 and 5),
  check (confidence >= 0 and confidence <= 1),
  check (last_seen_at >= first_seen_at)
);

create table if not exists public.alert_detections (
  alert_id uuid not null references public.alerts(id) on delete cascade,
  detection_id uuid not null references public.detections(id) on delete restrict,
  evidence_role text not null default 'supporting',
  primary key (alert_id, detection_id)
);

create table if not exists public.cases (
  id uuid primary key default gen_random_uuid(),
  jurisdiction_id uuid not null references public.jurisdictions(id),
  case_number text not null,
  title text not null,
  status public.case_status not null default 'live',
  priority smallint not null default 3,
  plate_token text,
  plate_masked text,
  opened_by uuid not null references auth.users(id),
  assigned_to uuid references auth.users(id),
  opened_at timestamptz not null default now(),
  due_at timestamptz,
  resolved_at timestamptz,
  resolution_summary text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (jurisdiction_id, case_number),
  check (priority between 1 and 5)
);

create table if not exists public.case_alerts (
  case_id uuid not null references public.cases(id) on delete cascade,
  alert_id uuid not null references public.alerts(id) on delete restrict,
  primary key (case_id, alert_id)
);

create table if not exists public.case_events (
  id bigint generated always as identity primary key,
  case_id uuid not null references public.cases(id) on delete cascade,
  actor_user_id uuid references auth.users(id),
  event_type text not null,
  note text,
  payload jsonb not null default '{}'::jsonb,
  occurred_at timestamptz not null default now()
);

create table if not exists public.audit_events (
  id bigint generated always as identity primary key,
  jurisdiction_id uuid references public.jurisdictions(id),
  actor_user_id uuid references auth.users(id),
  action text not null,
  resource_type text not null,
  resource_id text,
  purpose text,
  metadata jsonb not null default '{}'::jsonb,
  occurred_at timestamptz not null default now()
);

create index if not exists cameras_location_gix on public.cameras using gist (location);
create index if not exists detections_location_gix on public.detections using gist (location);
create index if not exists detections_live_idx on public.detections (jurisdiction_id, captured_at desc);
create index if not exists detections_day_idx on public.detections (jurisdiction_id, observed_on, captured_at desc);
create index if not exists detections_plate_timeline_idx on public.detections (jurisdiction_id, plate_token, captured_at) where plate_token is not null;
create index if not exists detections_camera_timeline_idx on public.detections (camera_id, captured_at desc);
create index if not exists alerts_queue_idx on public.alerts (jurisdiction_id, status, severity desc, last_seen_at desc);
create index if not exists cases_queue_idx on public.cases (jurisdiction_id, status, priority, opened_at desc);
create index if not exists audit_timeline_idx on public.audit_events (jurisdiction_id, occurred_at desc);

create or replace function public.set_observed_on()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.observed_on := (new.captured_at at time zone 'Asia/Kolkata')::date;
  return new;
end;
$$;

drop trigger if exists detections_set_observed_on on public.detections;
create trigger detections_set_observed_on
before insert or update of captured_at on public.detections
for each row execute function public.set_observed_on();

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists operator_profiles_set_updated_at on public.operator_profiles;
create trigger operator_profiles_set_updated_at before update on public.operator_profiles
for each row execute function public.set_updated_at();
drop trigger if exists cameras_set_updated_at on public.cameras;
create trigger cameras_set_updated_at before update on public.cameras
for each row execute function public.set_updated_at();
drop trigger if exists alerts_set_updated_at on public.alerts;
create trigger alerts_set_updated_at before update on public.alerts
for each row execute function public.set_updated_at();
drop trigger if exists cases_set_updated_at on public.cases;
create trigger cases_set_updated_at before update on public.cases
for each row execute function public.set_updated_at();

-- These views power the dashboard's Live Today and Recorded Days sections.
-- security_invoker makes the caller's RLS policies apply to underlying tables.
create or replace view public.live_today_detections
with (security_invoker = true)
as
select d.*
from public.detections d
where d.observed_on = (now() at time zone 'Asia/Kolkata')::date;

create or replace view public.historical_detections
with (security_invoker = true)
as
select d.*
from public.detections d
where d.observed_on < (now() at time zone 'Asia/Kolkata')::date;

create or replace view public.recorded_days
with (security_invoker = true)
as
select
  d.jurisdiction_id,
  d.observed_on,
  count(*)::bigint as detection_count,
  count(distinct d.camera_id)::bigint as active_camera_count,
  count(*) filter (where d.plate_token is not null)::bigint as readable_plate_count,
  count(*) filter (where d.is_watchlist_candidate)::bigint as watchlist_candidate_count,
  min(d.captured_at) as first_detection_at,
  max(d.captured_at) as last_detection_at
from public.detections d
group by d.jurisdiction_id, d.observed_on;

create or replace function public.current_operator_jurisdiction()
returns uuid
language sql
stable
security definer
set search_path = ''
as $$
  select p.jurisdiction_id
  from public.operator_profiles p
  where p.user_id = (select auth.uid()) and p.active
$$;

revoke all on function public.current_operator_jurisdiction() from public;
grant execute on function public.current_operator_jurisdiction() to authenticated;

alter table public.jurisdictions enable row level security;
alter table public.operator_profiles enable row level security;
alter table public.cameras enable row level security;
alter table public.registry_vehicle_snapshots enable row level security;
alter table public.detections enable row level security;
alter table public.detection_ocr_candidates enable row level security;
alter table public.alerts enable row level security;
alter table public.alert_detections enable row level security;
alter table public.cases enable row level security;
alter table public.case_alerts enable row level security;
alter table public.case_events enable row level security;
alter table public.audit_events enable row level security;

revoke all on table public.jurisdictions, public.operator_profiles, public.cameras,
  public.registry_vehicle_snapshots, public.detections, public.detection_ocr_candidates,
  public.alerts, public.alert_detections, public.cases, public.case_alerts,
  public.case_events, public.audit_events,
  public.live_today_detections, public.historical_detections, public.recorded_days
from anon, authenticated;
grant select on public.jurisdictions, public.operator_profiles, public.cameras,
  public.detections, public.detection_ocr_candidates, public.alerts,
  public.alert_detections, public.cases, public.case_alerts, public.case_events,
  public.live_today_detections, public.historical_detections, public.recorded_days
to authenticated;

create policy jurisdictions_select_own on public.jurisdictions
for select to authenticated
using (id = (select public.current_operator_jurisdiction()));

create policy profiles_select_self on public.operator_profiles
for select to authenticated
using (user_id = (select auth.uid()) and active);

create policy cameras_select_own_jurisdiction on public.cameras
for select to authenticated
using (jurisdiction_id = (select public.current_operator_jurisdiction()));

create policy detections_select_own_jurisdiction on public.detections
for select to authenticated
using (jurisdiction_id = (select public.current_operator_jurisdiction()));

create policy ocr_candidates_select_via_detection on public.detection_ocr_candidates
for select to authenticated
using (exists (
  select 1 from public.detections d
  where d.id = detection_id
    and d.jurisdiction_id = (select public.current_operator_jurisdiction())
));

create policy alerts_select_own_jurisdiction on public.alerts
for select to authenticated
using (jurisdiction_id = (select public.current_operator_jurisdiction()));

create policy alert_detections_select_via_alert on public.alert_detections
for select to authenticated
using (exists (
  select 1 from public.alerts a
  where a.id = alert_id
    and a.jurisdiction_id = (select public.current_operator_jurisdiction())
));

create policy cases_select_own_jurisdiction on public.cases
for select to authenticated
using (jurisdiction_id = (select public.current_operator_jurisdiction()));

create policy case_alerts_select_via_case on public.case_alerts
for select to authenticated
using (exists (
  select 1 from public.cases c
  where c.id = case_id
    and c.jurisdiction_id = (select public.current_operator_jurisdiction())
));

create policy case_events_select_via_case on public.case_events
for select to authenticated
using (exists (
  select 1 from public.cases c
  where c.id = case_id
    and c.jurisdiction_id = (select public.current_operator_jurisdiction())
));

-- Prototype Realtime: compact INSERT events only. At city scale, publish a reduced
-- event contract through Supabase Broadcast or the Python/Java realtime gateway.
do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'detections'
  ) then
    alter publication supabase_realtime add table public.detections;
  end if;
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'alerts'
  ) then
    alter publication supabase_realtime add table public.alerts;
  end if;
end $$;

comment on view public.live_today_detections is
  'Current India-calendar-day detections; automatically rolls over at midnight Asia/Kolkata.';
comment on view public.recorded_days is
  'Per-day archive index derived from the canonical detections event store.';
comment on table public.registry_vehicle_snapshots is
  'Backend-only authorized or synthetic registry responses. No owner identity in the prototype.';
